import { useEffect, useState, useSyncExternalStore } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import BattleScreen from '../components/BattleScreen';
import { attack, canRun, chooseEnemyMove, determineTurnOrder, getActionPriority, isFainted, useBattleItem } from '../game/battle.js';
import { averageLevel, createBattlePokemon } from '../game/pokemon.js';
import { getPokemon } from '../services/pokeapi';
import { gameStore } from '../store/gameStore';
const fallback = ['pidgey', 'rattata', 'pikachu', 'oddish'];
const pretty = (name) => name.charAt(0).toUpperCase() + name.slice(1);
export default function Battle() {
 const game=useSyncExternalStore(gameStore.subscribe,gameStore.getState,gameStore.getState), navigate=useNavigate(), encounter=game.run?.activeEncounter;
 const [party,setParty]=useState([]),[activeId,setActiveId]=useState(null),[enemy,setEnemy]=useState(null),[log,setLog]=useState([]),[menu,setMenu]=useState('main'),[loading,setLoading]=useState(true);
 const active=party.find(p=>p.id===activeId);
 useEffect(()=>{ if(!encounter||!game.run)return; let live=true; const avg=averageLevel(game.run.party); const offset=encounter.type==='boss'?3:encounter.type==='elite'?2:encounter.type==='trainer'?1:-1; const level=Math.max(1,avg+offset); const species=encounter.species??(encounter.boss?'gyarados':fallback[encounter.difficulty%fallback.length]); setParty(game.run.party.map(p=>createBattlePokemon(p,p.level??avg))); getPokemon(species).then(p=>{if(live){const foe=createBattlePokemon(p,level);setEnemy(foe);setActiveId(game.run.party[0].id);setLog([`${encounter.boss?encounter.trainer:'Wild'} ${pretty(foe.name)} appeared!`]);setLoading(false)}});return()=>{live=false}},[encounter?.id]);
 const commit=(nextParty,victory,defeated=null)=>{ gameStore.resolveRunEncounter({victory,party:nextParty,defeatedPokemon:defeated});navigate('/game'); };
 const enemyTurn=(me,foe,entries)=>{const move=chooseEnemyMove(foe,me,{trainer:encounter.type!=='wild'&&encounter.type!=='rare'});if(!move)return[me,foe];const hit=attack(foe,me,move);entries.push(hit.message??`${pretty(foe.name)} used ${pretty(hit.move.name)}!`);return[hit.defender,hit.attacker]};
 function useMove(move) { if (!active || !enemy) return; let me = active; let foe = enemy; const entries = []; const order = determineTurnOrder(me, foe, { priority: 0 }, { priority: 0 }); for (const side of order) { if (side === 'player') { const hit = attack(me, foe, move); me = hit.attacker; foe = hit.defender; entries.push(hit.message ?? `${pretty(me.name)} used ${pretty(move.name)}!`); if (hit.effectiveness === 2) entries.push("It's super effective!"); if (hit.effectiveness === 0) entries.push(`It doesn't affect ${pretty(foe.name)}...`); if (isFainted(foe)) break; } else { [me, foe] = enemyTurn(me, foe, entries); if (isFainted(me)) break; } } const next = party.map((p) => p.id === me.id ? me : p); setParty(next); setEnemy(foe); setLog((l) => [...l, ...entries]); setMenu('main'); if (isFainted(foe)) commit(next, true, foe); else if (isFainted(me)) { const replacement = next.find((p) => p.currentHp > 0); if (replacement) { setActiveId(replacement.id); setLog((l) => [...l, `${pretty(me.name)} fainted! Choose a replacement.`]); setMenu('party'); } else commit(next, false); } }
 function bag(item){if(item.includes('ball')&&encounter.type!=='wild'&&encounter.type!=='rare'){setLog(l=>[...l,'You cannot catch a trainer’s Pokémon!']);return}if(!gameStore.consumeItem(item)){setLog(l=>[...l,'You have none left!']);return}if(item.includes('ball')){const chance=.3+(1-enemy.currentHp/enemy.stats.hp)*.5+(enemy.status ? .1 : 0);if(Math.random()<chance){setLog(l=>[...l,`Gotcha! ${pretty(enemy.name)} was caught!`]);commit(party,true,enemy);return}setLog(l=>[...l,`${pretty(enemy.name)} broke free!`]);return}const result=useBattleItem(active,item);const next=party.map(p=>p.id===active.id?result.pokemon:p);setParty(next);setLog(l=>[...l,result.message]);setMenu('main');const entries=[];const [me,foe]=enemyTurn(result.pokemon,enemy,entries);setParty(next.map(p=>p.id===me.id?me:p));setEnemy(foe);setLog(l=>[...l,...entries])}
 if(!encounter)return <main className="page"><Link to="/game">Return to map</Link></main>; if(loading||!active||!enemy)return <main className="page"><p>PREPARING BATTLE…</p></main>;
 return <main className="page battle-page"><div className="battle-page__weather">{encounter.weather.toUpperCase()} · {encounter.type.toUpperCase()}</div><BattleScreen playerPokemon={active} wildPokemon={enemy} battleLog={log} menu={menu} onFight={() => setMenu('moves')} onMove={useMove} onBag={(item) => item ? bag(item) : setMenu('bag')} party={party} onSwitch={(id) => { const target = party.find((p) => p.id === id); setActiveId(id); setLog((l) => [...l, `Go, ${pretty(target.name)}!`]); setMenu('main'); }} onRun={() => { if (canRun({ player: active, enemy })) { setLog((l) => [...l, 'Got away safely!']); commit(party, true); } else { setLog((l) => [...l, "Couldn't escape!"]); } }} onBack={() => setMenu('main')} inventory={game.inventory} trainer={encounter.type !== 'wild' && encounter.type !== 'rare'} /></main>;
}
